apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: domain-migration-database-connection
  namespace: bulk-pack-services
spec:
  encryptedData:
    db: CHANGE_ME
  template:
    metadata:
      creationTimestamp: null
      name: domain-migration-database-connection
      namespace: domain-migration
