apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: migrate-regions
  labels:
    app: migrate-regions
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  schedule: '*/5 * * * *'
  startingDeadlineSeconds: 200
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: migrate-regions
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: doks.digitalocean.com/node-pool
                        operator: In
                        values:
                          - microservices-node-pool
          containers:
            - name: migrate-regions
              image: greenstand/domain-migration-scripts:TAG
              imagePullPolicy: IfNotPresent
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: database-connection
                      key: db
              command: ['npm', 'run', 'migrate-regions']
          restartPolicy: Never
